generator: admingenerator.generator.doctrine
params:
    model: Melody\UserBundle\Entity\Organization
    namespace_prefix: Melody\UserBundle
    concurrency_lock: ~
    bundle_name: MelodyUserBundle
    pk_requirement: \d+
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    nested_list:
        params:
            title: List for organization
            display: [name]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    list:
        params:
            title: List for organization
            display: [name]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params:
            display: [name]
        filename: ~
        filetype: ~
    filters:
        params:
            display: [name]
    new:
        params:
            title: New object for organization
            display: [name]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: Organization.title }|"
            display: [name]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Organization.title }|"
            display: [name]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
