generator: admingenerator.generator.doctrine
params:
    model: Melody\UserBundle\Entity\Person
    namespace_prefix: Melody\UserBundle
    concurrency_lock: ~
    bundle_name: MelodyUserBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for person
            display: [given_name,family_name,email,enabled]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: New object for person
            display: [username,email,enabled,plainPassword,given_name,family_name,gender,address,postal_code,city,country,birth_date,telephone,fax]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: Person.title }|"
            display: [username,email,enabled,plainPassword,given_name,family_name,gender,address,postal_code,city,country,birth_date,telephone,fax]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Person.title }|"
            display: [username,email,enabled,given_name,family_name,gender,address,postal_code,city,country,birth_date,telephone,fax]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
